### ISSUE TITLE
No UUID specified for label

### ISSUE THREAD

**Issue by alexander-arce** [neo4jrb/neo4apis-activerecord#11]
Hi,
I try to import data from _OpenErp/Odoo_. Models are generated using _Rmre_.
In my test, i want import data only from pos_order model, but process fail with message  
**No UUID specified for label `AccountJournal`**
Anyone trying to import data from OpenErp/Odoo?

**Comment by cheerfulstoic** [comment]
What command did you try running, or was it via Ruby code?  That error makes me think that it's trying to import all tables

**Comment by alexander-arce** [comment]
Hi @cheerfulstoic 
I try running 
_neo4apis activerecord models pos_order  --neo4j-url "http://xxxx:xx@localhost:7474" --identify-model --import-all-associations --debug_
Debug message is:

> Importing tables: pos_order
> include_list
> [:account_invoice, :account_journal, :account_move, :pos_order_lines, :pos_order_line_commissions, >:account_bank_statement_lines, :pos_session, :product_pricelist, :res_company, :res_partner, >:res_user, :sale_shop, :stock_picking]

Error message:

> /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-0.8.2/lib/neo4apis/base.rb:35:in `add_node': No UUID specified for label`AccountJournal`(ArgumentError)
> from /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/activerecord.rb:63:in`add_model_node'
> from /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/activerecord.rb:51:in `add_model_relationship'
> from /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/activerecord.rb:35:in`block (2 levels) in model_importer'
> from /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/activerecord.rb:30:in `each'
> from /home/aletz/.rvm/gems/ruby-2.2.0/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/activerecord.rb:30:in`block in model_importer'
> Thanks

**Comment by cheerfulstoic** [comment]
Ah, got it, I think it's because it's trying to load associations.  In this case the `PosJournal` model (I think) has an association to the `AccountJournal`.

Is `account_journal` a many-to-many table, maybe?  Does it have a primary key?

**Comment by alexander-arce** [comment]
Yes PosOrder has an association to the AccountJournal.
AccountJournal has a primary key.
I'm attaching files for model definition according to debug message.
[pos_order.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40721/pos_order.txt)
[account_bank_statement_line.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40325/account_bank_statement_line.txt)
[account_invoice.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40326/account_invoice.txt)
[account_journal.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40341/account_journal.txt)
[account_move.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40329/account_move.txt)
[pos_order_line.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40331/pos_order_line.txt)
[pos_order_line_commission.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40332/pos_order_line_commission.txt)
[pos_session.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40333/pos_session.txt)
[product_pricelist.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40334/product_pricelist.txt)
[res_company.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40336/res_company.txt)
[res_partner.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40337/res_partner.txt)
[res_user.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40335/res_user.txt)
[sale_shop.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40339/sale_shop.txt)
[stock_picking.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40338/stock_picking.txt)

_Sql definition for AccountJournal:_
[account_journal.sql.txt](https://github.com/neo4jrb/neo4apis-activerecord/files/40342/account_journal.sql.txt)

**Comment by alexander-arce** [comment]
I attach images of relations for pos_order

> Foreign keys
> ![pos_order_foreign_keys](https://cloud.githubusercontent.com/assets/5661038/11306799/a6cc515a-8f79-11e5-9b82-7bcf39ac6741.png)
> Dependencies
> ![pos_order_dependencies](https://cloud.githubusercontent.com/assets/5661038/11306801/a8ca6938-8f79-11e5-92de-3b8ad64e3ef5.png)
