### ISSUE TITLE
Cannot load such file -- neo4j-server

### ISSUE THREAD

**Issue by CraigSnowden** [neo4jrb/neo4apis-activerecord#13]
Is there a dependency missing here?

```
neo4apis activerecord all_tables --import-all-associations
requiring neo4apis-activerecord
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      multi_json (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Importing tables: [...]
~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- neo4j-server (LoadError)
    from ~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    from ~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from ~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4j-core-6.1.4/lib/neo4j/session.rb:102:in `open'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4apis-0.9.1/lib/neo4apis/cli/base.rb:10:in `specified_neo4j_session'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/cli/activerecord.rb:108:in `neo4apis_client'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/cli/activerecord.rb:74:in `import_models_or_tables'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4apis-activerecord-0.9.1/lib/neo4apis/cli/activerecord.rb:45:in `all_tables'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from ~/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from ~/.rvm/gems/ruby-2.3.1/gems/neo4apis-0.9.1/bin/neo4apis:15:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.3.1/bin/neo4apis:22:in `load'
    from ~/.rvm/gems/ruby-2.3.1/bin/neo4apis:22:in `<main>'
    from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cheerfulstoic** [comment]
Hrmm, I that's strange.  That's this line:

https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j/session.rb#L102

Trying to load this file:

https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j-server.rb

Both are in the same gem...

Did you `bundle install` first?
